name: CI tests
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install valgrind
      run: |
         sudo apt update
         sudo apt install -y valgrind
    - name: Build and test
      run: |
         make
         make test
         make leakcheck
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
         make
         make test
